### ISSUE TITLE
Add clip argument to oe_get()

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmextract#178]
The example here shows the functionality: https://docs.ropensci.org/osmextract/articles/osmextract.html#vectortranslate_options

```r
la_valletta = st_sfc(st_point(c(456113.1, 3972853)), crs = 32633) %>%
  st_buffer(5000)

# 2. Define the vectortranslate options
my_vectortranslate = c(
  "-f", "GPKG", 
  "-overwrite", 
  "-t_srs", "EPSG:32633",
  "-select", "highway",
  "-where", "highway IN ('primary', 'secondary', 'tertiary', 'unclassified')",
  "-clipdst", st_as_text(la_valletta),
  "-nlt", "PROMOTE_TO_MULTI",
  "lines"
)
```

I think it would be good to expose a `clipdst` argument, that could take an sf object directly. Thoughts @agila5 ?

Use case: getting data for specific cities in a country like India that seems to have few (if any) subdivisions, meaning reading in GB of data without a spatial filter.

**Comment by agila5** [comment]
Hi @Robinlovelace. Yes, I like the idea, which is also linked with #142. I'm a little busy these days (fixing the last parts of PhD dissertation for the defence) but I will tackle both issues as soon as possible.

**Comment by agila5** [comment]
One question. There are several arguments in `ogr2ogr` that could be useful during the vectortranslate process (e.g. `-where`, `-clipsrc`, `-clidst`, `-select`, `-sql`, `-select` ecc). I don't like the idea of creating an ad-hoc argument in `oe_vectortranslate()` for each `ogr2ogr` argument, since that may be really confusing. So I think that the arguments for `ogr2ogr` could be specified using a named list. For example: 

``` r
oe_get("somewhere", vectortranslate_options = list(where = "some query", clipsrc = some-polygon))
```

The default value for `vectortranslate_options` is `list()`, which implies that the options are automatically set by the function (i.e. the current behaviour). Opinions?

**Comment by Robinlovelace** [comment]
A named list sounds sensible to me.

**Comment by luukvdmeer** [comment]
What about arguments without a value, like `--overwrite`? Maybe makes sense to use boolean values for those, like in `list(overwrite = TRUE)`? And for the 'Open options' and 'Layer creation options' use nested lists?

I think it is clearer than the current structure with `c()`. And also much easier to check if a certain option is in there or not.

**Comment by Robinlovelace** [comment]
Sounds like a new function would be good, e.g.:

```r
od_list_to_query(list = NULL) {
  # ...
}
```

**Comment by Robinlovelace** [comment]
Current functionality on the `oe_query` branch:

```
> oe_query(query_list = list(overwrite = TRUE))
[1] "--overwrite"
> oe_query(query_list = list(overwrite = TRUE, f = "GPKG"))
[1] "--overwrite -f GPKG"
> oe_query(query_list = list(f = "GPKG", t_srs = "EPSG:32633"))
[1] "-f GPKG -t_srs EPSG:32633"
```

**Comment by Robinlovelace** [comment]
Woops, previous commit crashed R. Any ideas?

![image](https://user-images.githubusercontent.com/1825120/117187774-2e83e580-add4-11eb-972a-57c5b3ccaa57.png)

**Comment by Robinlovelace** [comment]
Changing tack after reading: https://r-spatial.github.io/sf/reference/gdal_utils.html

**Comment by Robinlovelace** [comment]
Latest example - not sure what is failing here, any ideas Andrea?

```
> oe_vtlist(vtlist = list(overwrite = TRUE))
[1] "--overwrite"
> oe_vtlist(vtlist = list(overwrite = TRUE, f = "GPKG"))
[1] "--overwrite" "-f"          "GPKG"       
> oe_vtlist(vtlist = list(f = "GPKG", t_srs = "EPSG:32633"))
[1] "-f"         "GPKG"       "-t_srs"     "EPSG:32633"
> its = oe_get("ITS Leeds", quiet = FALSE, download_directory = tempdir())
> # mapview::mapview(its[1:5, ]) # find suitable subset
> its_sample_union = sf::st_union(its[1:5, ])
although coordinates are longitude/latitude, st_union assumes that they are planar
> its_polygon = sf::st_convex_hull(its_sample_union)
> its_poly_txt = sf::st_as_text(its_polygon)
> q = oe_vtlist(list(clipdst = its_poly_txt))
> q
[1] "-clipdst"                                                                                                                                                                                   
[2] "POLYGON ((-1.552587 53.80712, -1.559842 53.80812, -1.559919 53.80814, -1.5609 53.80851, -1.560995 53.81077, -1.561004 53.81102, -1.558487 53.81044, -1.551771 53.8073, -1.552587 53.80712))"
```

**Comment by Robinlovelace** [comment]
That's where I've got to, not sure what to try next other than adding a `layer = "lines"` argument...

**Comment by agila5** [comment]
Hi @Robinlovelace! The problem with your approach is that the input to `gdal_utils` must always be a "complete" query otherwise `gdal_utils` crashes the R session (see also https://github.com/ropensci/osmextract/issues/183). 

So I was thinking that we could adopt the following approach: 

1. The arguments to `vectortranslate_options` can be specified using a character vector (so ignore the list approach); 
2. The "basic" elements for `vectortranslate_options` are `c("-f", "GPKG", "-overwrite", layer)`, so if `vectortranslate_options` is `NULL` (the default), then `gdal_utils` is run with `c("-f", "GPKG", "-overwrite", layer)`; 
3. If the user set `vectortranslate_options = c("-t_srs", "EPSG:32633")` or `vectortranslate_options = c("-clipdst", something)`, then the "basic" elements are added by `oe_vectortranslate` and `gdal_utils` is run with `c("-f", "GPKG", "-overwrite", layer, "-t_srs", "EPSG:32633")`. 

I think that this is more intuitive than the list approach. The only problem is that the choice of "basic" elements is quite arbitrary, but I think that `c("-f", "GPKG", "-overwrite", layer)` is a reasonable compromise. Do you like the idea?

**Comment by Robinlovelace** [comment]
Hi @agila5, I really like the idea. I think the work I've done on `oe_vlist()` could still be useful though. Inside the relevant function (`oe_read()`?) there could be something like:

```
if(class(vectortranslate_options) == "list") {
  vectortranslate_options = c("-f", "GPKG", "-overwrite", layer, `oe_vlist(vectortranslate_options)`
} else {
 ...
}
```

Giving maximum flexibility to the user, enabling the user to specify a char vector (1), ensuring the basics are in there, although it may be worth doing some sanity checks to avoid R crashes :bomb: (2) and :+1: for (3).

**Comment by agila5** [comment]
Are you sure that you pushed all changes? I don't see `oe_vtlist` anywhere in the PR or the branch.

**Comment by Robinlovelace** [comment]
> Are you sure that you pushed all changes? I don't see `oe_vtlist` anywhere in the PR or the branch.

Aha. Woops. Just pushed!

**Comment by agila5** [comment]
TODO: implement the "list" options and explore the pros and cons

**Comment by Robinlovelace** [comment]
Building on comments in https://github.com/ropensci/osmextract/pull/200 I realise there is already an open issue on a 'clip' type argument that takes an `sf` object as an input. Regarding the comment:

> The only problem I see here is that there are several options in `ogr2ogr` that could be interpreted as "spatial boundary" (i.e. `-spat`, `-clipsrc`, `-clipdst` , `-sql` + spatiallite) and I'm not sure what's the best option (probably `-spat`). Feel free to create a new issue if you want.

Good point. There could be a generic `clip = `sf_object` arg and then another like `clip_type = "spat"` by default.

Hence change of issue title. Thoughts @agila5 ? There are already lots of arguments and I'm aware of the issue of 'mission creep' but my guess is that this one could be worth it. May be other solutions, including just better documentation of using these various spatial boundary options.
