### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmextract#92]
Here are some ideas from my friend and housemate Pete:

![image](https://user-images.githubusercontent.com/1825120/88385330-075caa00-cda6-11ea-94fb-639e3f2b9e29.png)

**Comment by agila5** [comment]
I didn't forget about the logo and I'd choose the top-left one. Maybe, if your roommate can help us again (btw: please thank him on my behalf) and as a hidden "bonus", I think it would be even better if the image depicted the WKB representation of Leeds' centroid instead of generic 0s and 1s: 

``` r
sf::st_as_binary(sf::st_geometry(osmextract:::oe_search("Leeds")))
#> [[1]]
#>  [1] 01 01 00 00 00 c2 1f 34 71 61 b3 f8 bf d9 5c 35 cf 11 e6 4a 40
#> 
#> attr(,"class")
#> [1] "WKB"
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hence, it could represent 01 01 00 00 00 in the first diagonal and so on. If Pete can't work on these ideas anymore, I'd simply choose the top-left image which is already really good!

**Comment by Robinlovelace** [comment]
Will ask Pete...

**Comment by Robinlovelace** [comment]
> I'd choose the top-left one.

I agree. No harm in doing a poll also...

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/200123543-6c674448-1530-4ccc-821b-4242c13997dc.png)

**Comment by Robinlovelace** [comment]
Final version as a .png:

![image](https://user-images.githubusercontent.com/1825120/200123605-1349adbe-41a0-4fd0-a23e-99b62b4f75ae.png)
